# ln $HOME/clone/pybind11_scons/Dockerfile_clang-tidy.txt Dockerfile
# docker build -t pybind11_clang-tidy .
# rm Dockerfile

# docker run --rm -v $HOME/forked/pybind11:/mounted_pybind11 -it pybind11_clang-tidy
# cmake -S /mounted_pybind11/ -B build -DCMAKE_CXX_CLANG_TIDY="$(which clang-tidy);-fix" -DDOWNLOAD_EIGEN=ON -DDOWNLOAD_CATCH=ON -DCMAKE_CXX_STANDARD=17
# cmake --build build -j 16 -- --keep-going

FROM silkeh/clang:12
RUN apt-get update && apt-get install -y python3-dev python3-pytest vim
